# Licensed under the Apache License: http://www.apache.org/licenses/LICENSE-2.0
# For details: https://github.com/nedbat/coveragepy/blob/master/NOTICE.txt

name: "Coverage"

on:
  push:
    branches: ["master"]
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  coverage:
    name: "Coverage on Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version:
          - "2.7"
          - "3.5"
          - "3.9"
      fail-fast: false

    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install -r requirements/ci.pip
          python -m pip install -c requirements/pins.pip tox-gh-actions

      - name: "Run tox for ${{ matrix.python-version }}"
        env:
          COVERAGE_COVERAGE: "yes"
        run: |
          set -xe
          python -m tox
          ls -al .*cov*
          python -m igor combine_html
          ls -al .*cov*
          python -m coverage xml
          ls -al .*cov*

      - name: "Upload to codecov"
        uses: codecov/codecov-action@v1
        with:
          file: coverage.xml
